"""v1

Revision ID: 29b2c7de3df8
Revises: 
Create Date: 2020-02-14 17:15:30.268172

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '29b2c7de3df8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('listing',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('imported_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('host_id', sa.Integer(), nullable=True),
    sa.Column('host_name', sa.String(), nullable=True),
    sa.Column('neighbourhood_group', sa.String(), nullable=True),
    sa.Column('neighbourhood', sa.String(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('room_type', sa.Enum('default', 'unknown', 'entire', 'private', 'shared', name='roomtype'), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('minimum_nights', sa.Integer(), nullable=True),
    sa.Column('number_of_reviews', sa.Integer(), nullable=True),
    sa.Column('last_review', sa.DateTime(), nullable=True),
    sa.Column('reviews_per_month', sa.Float(), nullable=True),
    sa.Column('calculated_host_listings_count', sa.Integer(), nullable=True),
    sa.Column('availability_365', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('listing')
    # ### end Alembic commands ###
